### ISSUE TITLE
Add Grid.__populate_lonlat_coord/ Grid.__populate_cartesian_xyz_coord

### ISSUE THREAD

**Issue by hongyuchen1030** [UXARRAY/uxarray#143]
`Grid.__populate_cartesian_xyz_coord`: 

        A helper function that populates the xyz attribute in Mesh.ds
      use case: If the grid file's Mesh2_node_x 's unit is in degree

`Grid.__populate_lonlat_coord`:
         Helper function that populates the longitude and latitude and store it into the Mesh2_node_x and Mesh2_node_y
          use case: If the grid file's Mesh2_node_x 's unit is in meter

**Comment by erogluorhan** [comment]
Hi @hongyuchen1030 , I now notice we had never merged a PR (PR #145 was closed instead of being merged) on this (probably because of the code structure change). Therefore, instead of creating a new issue, I reopened this after yesterday's talk. 

If my understanding is correct, could you add your `__populate_lonlat_coord` and `__populate_cartesian_xyz_coord` functions in a new PR linkinging to this issue?

**Comment by hongyuchen1030** [comment]
> Hi @hongyuchen1030 , I now notice we had never merged a PR (PR #145 was closed instead of being merged) on this (probably because of the code structure change). Therefore, instead of creating a new issue, I reopened this after yesterday's talk.
> 
> If my understanding is correct, could you add your `__populate_lonlat_coord` and `__populate_cartesian_xyz_coord` functions in a new PR linkinging to this issue?

Thank you very much! Sure, I will create a new PR linking to this issues
