### ISSUE TITLE
Grid.build_face_edges_connectivity 

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#205]
Implement `Grid.build_face_edges_connectivity `

**Comment by philipc2** [comment]
Have you had a look at the `xugrid` implementation for this (and other) associated connectivity functions? I'm currently taking some time to review #191 and familiarize myself with `xugrid` since much of the initial discussion about this package was prior to me joining the team last summer. 

I'll also ping @Huite for any feedback and to start up a similar discussion to https://github.com/UXARRAY/uxarray/issues/130#issuecomment-1257828448

**Relevant References** 

https://github.com/UXARRAY/uxarray/issues/19#issuecomment-1034754576

https://deltares.github.io/xugrid/examples/connectivity.html

https://github.com/Deltares/xugrid/blob/main/xugrid/ugrid/connectivity.py#L231

**Comment by hongyuchen1030** [comment]
Thank you for your information. I will take a look at it.

**Comment by hongyuchen1030** [comment]
After studying the XUGRID, I have some questions:

1. How did it deal with the dummy nodes from the face_node_connectivity?
After reading through the [close_polygons](https://github.com/Deltares/xugrid/blob/9741f5bdc47a8f500ba1e562d54fa20b01dd1b9c/xugrid/ugrid/connectivity.py#L173)

I noticed that the `face_node_connectivity` cannot have the same `Fill_Value` as the `def close_polygons(face_node_connectivity: IntArray, fill_value: int)` used. But according to the UXARRAY documentation, the input
face_node_connectivity` will have Fill_values. #189 


For example
`face_node_connectivity = [[0, 1, 2, 3],
                                                 [1, 4, 3, 5],
                                                  [2, 4, 3 -1]] # The original face_node_connectivity, the last face has the Fill_Value as -1
`
If the user called `close_polygons(face_node_connectivity`,  fill_value=`-1`)`Then after line 178(https://github.com/Deltares/xugrid/blob/9741f5bdc47a8f500ba1e562d54fa20b01dd1b9c/xugrid/ugrid/connectivity.py#L173) here, it will become
`closed = [[0, 1, 2, 3, -1],
                                                 [1, 4, 3, 5, -1],
                                                  [2, 4, 3 -1, -1]] # Fill the last indice as -1
`
And after line181:
`closed = [[0, 1, 2, 3, 0],
                                                 [1, 4, 3, 5, 0],
                                                  [2, 4, 3 2, 2]] # It will replace every -1 with the `first_node`
`
Which apparently is not what we want for the last face. Since it also replace its `Fill_Value` with the `first_node`

**Comment by Huite** [comment]
Hi @hongyuchen1030 

Do you have specific questions?

I'll just make a couple of remarks here, also from briefly reading through #189.

* The face_node_connectivity is fundamentally an indexing array. As you cannot index with floating point arrays, you'd regularly have to convert to integer arrays, possibly dropping the fill values. Unfortunately, given a _FillValue, xarray will convert it to floats, with NaNs as the fill value. In my setup, I separate the UGRID variables from the other variables and stuff it into a separate  topology object. I do the conversion to integer there: https://github.com/Deltares/xugrid/blob/8168ece26465b565382b85a4a07b151d5d0a9845/xugrid/ugrid/ugridbase.py#L295
(In my case, I expected the user to really not see the connectivity arrays.)
* I've chosen for a default value of -1. -1 is a valid indexer in Python, and I've been bitten a few times by it. Of course a fill value is just that, a fill value. As long as it's not in the range of the valid indexes (0 .. n_face), it's not a problem. Probably the best choice is something that will error: e.g. `np.iinfo(np.int32).min` or `np.iinfo(np.int32).max` (or the 64 bit version). This could be easily changed by introducing a `DEFAULT_FILL_VALUE` constant.
* Note that a negative value is not a valid indexer in e.g. Fortran, so except for the fill_value, the face_node_connectivity array shouldn't contain negative numbers!
* I don't think you understand the purpose of the `close_polygons` function. The only reason I use this, is so that I can do the vectorized numpy operations afterwards. Because I sort row by row, then call call np.unique afterwards, the duplicates that are introduced here are removed anyway, but it also ensures an edge is created between the first and the last node.
* Note that duplicating vertices works in many cases: I also use this approach to compute the face area. (Because a triangle with two duplicated vertices will have an area of 0): https://github.com/Deltares/xugrid/blob/main/xugrid/ugrid/connectivity.py#L311

You also ask about numba in #202. Numba primarily works with numpy arrays. It understands (reimplements) many numpy functions and methods. I've chosen to use mostly vectorized numpy (and scipy sparse) function. This results in a significantly shorter code, but it's not necessarily much more readable. But if you're dealing with permutations of permutations, it's not trivial to keep in mind anyway.

The biggest upside of numba is that you don't allocate a lot of temporary arrays like you have to with numpy (e.g. creating an index array). The downside is that you run into compilation overhead (although you can cache with numba). However, you're mostly sorting and getting unique values (which can be easily done from sorted arrays: see https://github.com/EelcoHoogendoorn/Numpy_arraysetops_EP). I'm quite confident the numpy sorting functions are performant.

I see you're using a Python set to find uniques. I recommend you benchmark it: I would it expect it to be much slower than the numpy unique approach (make sure you test with a large enough grid).

**Comment by hongyuchen1030** [comment]
Hi @Huite 

Thank you so much for your explanation, that helps a lot.

I think my understanding of the `close_polygons` function is the same as yours. Just that since the `face_node_connectivity` in our project will contain `_Fill_Value_`, some of your implementation might not be compatible with ours.

And thank you for the information about `np. unique`, I will think about how to better utilize the `numpy` function in my implementation.
