### ISSUE TITLE
MPAS Usage Example Notebook 

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#249]
Showcase newly added support for working with MPAS grids in UXarray

### Outline
* Quick description of the MPAS Specifications and how they map to the UGRID conventions (table, diagram)
* Using UXarray to load the Primal and Dual meshes 
* Basic visualizations (via external code, not directly through UXarray)

**Comment by philipc2** [comment]
@xylar @cdeciampa 

Other than the test dataset in #228, any additional datasets that I could use for this usage example would be great to have. 

Also, let me know if there is anything specific you'd like me to cover in this example other than what's in the outline.

**Comment by xylar** [comment]
@philipc2, we have several ocean meshes of varying sizes and types here:
https://web.lcrc.anl.gov/public/e3sm/mpas_standalonedata/mpas-ocean/mesh_database/
I would suggest using at least one of the doubly periodic planar meshes, since that tests a different type of mesh than the spherical mesh you already have.  Maybe [doubly_periodic_10km_160x500km_planar.151001.nc](https://web.lcrc.anl.gov/public/e3sm/mpas_standalonedata/mpas-ocean/mesh_database/doubly_periodic_10km_160x500km_planar.151001.nc) is small enough to not be inconvenient but big enough to not be completely boring?

There are also ice-sheet meshes here:
https://web.lcrc.anl.gov/public/e3sm/mpas_standalonedata/mpas-albany-landice/
They could be interesting for variety.

**Comment by xylar** [comment]
If you want something bigger (and scientifically more interesting), these are the meshes we actually use in production E3SM simulations:
https://web.lcrc.anl.gov/public/e3sm/inputdata/share/meshes/mpas/ocean/

**Comment by philipc2** [comment]
@xylar Thank you very much for these!

**Comment by cdeciampa** [comment]
@philipc2 Just saw this, I can provide a variable-resolution (60km-3km) sample file for MPAS-A with refinement over Florida-ish, but it's ~1GB for the data file and ~8GB for the mesh.

**Comment by philipc2** [comment]
> @philipc2 Just saw this, I can provide a variable-resolution (60km-3km) sample file for MPAS-A with refinement over Florida-ish, but it's ~1GB for the data file and ~8GB for the mesh.

I'd love to play around with that data anyways, especially for some performance tests.
