### ISSUE TITLE
FVCOM

### ISSUE THREAD

**Issue by iuryt** [UXARRAY/uxarray#26]
Hey! Great repository.

I recently created a repo to help people to access and analyze FVCOM data (https://github.com/iuryt/FVCOMpy)
I first thought about finding ways to interpolate or average the data to a regular grid to use `xarray` for further analyses, but then I understand that it defeats part of the purpose of the unstructured grid. 

How to compute horizontal gradients and make it work for data visualization packages as `matplotlib`?

**Comment by erogluorhan** [comment]
Hi @iuryt , thanks a lot for reaching out! Great, informative README in your repo that states the objective and details very well! 

Yes, we agree with your understanding, and because of that, UXarray aims at implementing the analysis operators on the native grid itself, not on a regular grid after a conversion. Please check our [draft API](https://github.com/UXARRAY/uxarray/blob/main/docs/user_api/uxarray_api.md) to see we have the gradient functions on our roadmap, too, but it is a bit early to talk specifics about it. Please also feel free to propose any idea on our draft API.
