### ISSUE TITLE
Tracking behavior of inherited methods and attributes

### ISSUE THREAD

**Issue by anissa111** [UXARRAY/uxarray#272]
Here are some documentation to track the functionality status of methods we're inheriting from xarray

Part of #216 

- [tracking spreadsheet](https://docs.google.com/spreadsheets/d/1zW9jWCz26Gw5DL6jnZk_QWa-LDmHSmbo1KVKKoBv5tY/edit?usp=sharing)
- [raw jupyter notebook](https://github.com/NCAR/geocat-scratch/blob/anissa/anissa/ux_redesign.ipynb)

**Comment by erogluorhan** [comment]
Hey @philipc2 , assigned this to you per today's action items.

**Comment by philipc2** [comment]
@erogluorhan @anissa111 

I've compiled a notebook highlighting a few observations that I made after revisting the spreadsheet. It can be found [here](https://github.com/NCAR/geocat-scratch/blob/52693a6d24b13630a402172daa1bef0a5fa4b908/uxarray-redesign/redesign_workflow.ipynb).

Here are a few takeaways:
* The majority of the functions that were breaking due to the `uxgrid` accessor attribute not existing (`AttributeError: 'UxDataset' object has no attribute 'uxgrid'`) now have a `uxgrid` attribute, however it is now stored being stored as `None` after executing a function that returns either a `ux.Dataset` or `ux.DataArray`. A few exceptions to this can be seen in the notebook above
* Other than the issue above, most basic arithmetic, logical, and manipulation functions/operators are executing and outputting the correct results
* By default, our `copy` method for `ux.Dataset` and `ux.DataArray` performs a deep copy
* When creating a deep copy of a `ux.DataArray` outside of the scope of the `ux.Dataset` that it originated from, it is successfully linked with a new grid object. However, if we then attempt to insert this new data array back into the dataset, its grid object is again linked back to the primary one stored in the dataset. Comparing the results both within and outside the dataset of the same data array showcase this. I agree that all data arrays part of a data set should use the same grid as the data set, but this could lead to some bugs/confusion with how we are currently handling (maybe raise an exception if we attempt to insert a data variable who's grid is not the same as the source data set?)

**Comment by erogluorhan** [comment]
Hey @philipc2 , thansk for the notebook! Its findings are much helpful, and I am working on them

**Comment by philipc2** [comment]
> Hey @philipc2 , thansk for the notebook! Its findings are much helpful, and I am working on them

Of course! Let me know if there is anything I can help with or elaborate on!

**Comment by erogluorhan** [comment]
> * The majority of the functions that were breaking due to the `uxgrid` accessor attribute not existing (`AttributeError: 'UxDataset' object has no attribute 'uxgrid'`) now have a `uxgrid` attribute, however it is now stored being stored as `None` after executing a function that returns either a `ux.Dataset` or `ux.DataArray`. A few exceptions to this can be seen in the notebook above

This has been fixed now by overriding `_replace` for both UxDataset and UxDataArray. 

The issue with the arithmetic operators and `to_array` is that their return obj types are xr.Dataset and xr.DataArray instead of ux.UxDataset and ux.UxDataArray, respectively. I don't see it as vital, and I believe it can even be addressed after a merge, but I will still keep looking into them tomorrow.

**Comment by philipc2** [comment]
> > * The majority of the functions that were breaking due to the `uxgrid` accessor attribute not existing (`AttributeError: 'UxDataset' object has no attribute 'uxgrid'`) now have a `uxgrid` attribute, however it is now stored being stored as `None` after executing a function that returns either a `ux.Dataset` or `ux.DataArray`. A few exceptions to this can be seen in the notebook above
> 
> This has been fixed now by overriding `_replace` for both UxDataset and UxDataArray.
> 
> The issue with the arithmetic operators and `to_array` is that their return obj types are xr.Dataset and xr.DataArray instead of ux.UxDataset and ux.UxDataArray, respectively. I don't see it as vital, and I believe it can even be addressed after a merge, but I will still keep looking into them tomorrow.

Great work on the fix! It behaving as expected for me locally now. I

**Comment by erogluorhan** [comment]
> The issue with the arithmetic operators and `to_array` is that their return obj types are xr.Dataset and xr.DataArray instead of ux.UxDataset and ux.UxDataArray, respectively. I don't see it as vital, and I believe it can even be addressed after a merge, but I will still keep looking into them tomorrow.

An update: Missing `uxgrid` issue with `to_array()` and arithmetic operators has also been resolved now with the commit [9af34e5](https://github.com/UXARRAY/uxarray/pull/216/commits/9af34e5b0589a2896beab7848338eb9b296bcdd1)

**Comment by philipc2** [comment]
Adressed by #216
