### ISSUE TITLE
Populate `edge_node_distances`

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#525]
`Grid.Mesh2_edge_node_distances` contains the distance between the two nodes that saddle a given edge. We should be able to populate this variable by parsing over either the `(lat, lon)` or `(x, y, z)` coordinates of the two edges and compute the distance.

**Comment by philipc2** [comment]
@hongyuchen1030 

For computing the distance between the nodes the saddle an edge, we should treat the edge as a Great Circle Arc, correct?

Do you have any tips on the best approach to implement this? Would using the haversine formula for computing the distance between the nodes that make up an arc be appropriate?

**Comment by hongyuchen1030** [comment]
> @hongyuchen1030
> 
> For computing the distance between the nodes the saddle an edge, we should treat the edge as a Great Circle Arc, correct?
> 
> Do you have any tips on the best approach to implement this? Would using the haversine formula for computing the distance between the nodes that make up an arc be appropriate?

All edges in our project should either be a great circle arc or a constant latitude. And for user's input, all edges will be considered as a Great Circle Arc on a unit sphere. The "constant latitude" edges are used rarely and only used for query so far.

And haversine formula gave the shortest distance on the sphere for any two nodes. You can try to use that formula here if you just want to give a rough idea about the distance of two nodes.

However, due to the native of the floating point calculation, such distance should be used as a reference only. So it really depends on what're your expectations for this functionality.

**Comment by hongyuchen1030** [comment]
The floating point error example here is:

If we said we divided the equator into 4 edges: A, B, C, D. And each edge is formed by its two nodes: A1, A2, B1, B2,...

Does your calculative result shows

dis_{A1, A2} + dis_{B1, B2} + dis_{C1, C2} +  dis_{D1, D2} = 2 * `np.pi` * 1.0?

If not, what is the error here? I feel like this is the part we need to be careful about
