### ISSUE TITLE
Revisit Matplotlib Support for Plotting

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#840]
#839

**Comment by rljacob** [comment]
What I think users want is uxarray  --> matplotlib without going through holoviews.  Can we do that?

**Comment by rajeeja** [comment]
> What I think users want is uxarray --> matplotlib without going through holoviews. Can we do that?

May be issue a warning or something that points the users towards holoviews, we use it because of xarray support, interactive and ability to large datasets and utilize dask..

**Comment by rljacob** [comment]
Many climate use cases involve making figures from scripts  so interactive is not a requirement.

**Comment by philipc2** [comment]
> Many climate use cases involve making figures from scripts so interactive is not a requirement.

HoloViews isn't just used for interactive plots. It can be used with the Matplotlib backend to generate figures from scripts, as can be seen in #843

**Comment by xylar** [comment]
@philipc2, we working on MPAS (Model for Prediction Across Scales) visualization have found HoloViews to be pretty counterintuitive, hard to configure and hard to get to behave as we need it to.  The interactivity is not something we take advantage of very often, so that isn't a plus for us.  The lack full integration of cartopy and projections seems to be a big downside for us.  In addition, HoloViews has a very different  interface form matplotlib (so a big learning curve and porting cost) and and is separated by many levels of (often poorly documented) code from the associated matplotlib calls.  While we can sometimes use HoloViews plot figures that are "good enough" for debugging purposes, we have not had much luck when we try to incorporate them into our automated analysis pipeline or to make publication-quality figures.

We are getting around this by writing our own code (planned for https://github.com/E3SM-Project/mosaic) to handle polygon collections directly with `matplotlib` and `cartopy` but not using HoloViews.  Our plan is to develop this capability for a bit with MPAS meshes in mind but then to suggest it as an alternative approach for UXarray if and when we can demonstrate its success.

**Comment by whannah1** [comment]
> The lack full integration of cartopy and projections seems to be a big downside for us.

IMO this is the only issue that matters for wider adoption.

**Comment by xylar** [comment]
> The lack full integration of cartopy and projections seems to be a big downside for us.

I know that GeoViews is supposed to take care of this but this hasn't been anywhere near seamless in your testing so far.

**Comment by philipc2** [comment]
Thanks for the feedback all! 
* We will look into better supporting `UxDataArray.to_polycollection()` and `Grid.to_linecollection()` methods (which we do currently roughly support, but have not done any testing since the last time we look at it with our 2023 SIParCS intern). We we look into getting some documentation into our User Guide on these methods. Our main reason for not moving forward with using Matplotlib directly was the less than ideal performance for visualizing high resolution grids. 
* Our Point plotting does support Cartopy projections, however our Polygon methods do not have projection support yet. We will look into getting better compatibility with GeoViews

**Comment by philipc2** [comment]
Here's a minimal example of plotting the grid using out `to_linecollection()` method. 
```Python
# Conversion to Line Collection
lc = uxds.uxgrid.to_linecollection()

plt.figure(figsize=(6, 4))
ax = plt.axes(projection = ccrs.PlateCarree())
ax.coastlines()
ax.set_extent((-110, -50, 0, 40))
ax.add_collection(lc)
plt.title("Line Collection Plot")
```

<img width="448" alt="image" src="https://github.com/UXARRAY/uxarray/assets/67855069/8b0e0c98-baf3-4faa-b425-a1e3b95cd418">

**Comment by philipc2** [comment]
Another example using our `to_polycollection()` method.

```Python
pc, _ = uxds['SFCO2'][0].to_polycollection()

pc.set_transform(ccrs.PlateCarree())
plt.figure(figsize=(20, 10))
ax = plt.axes(projection=ccrs.Robinson())
pc.set_cmap("inferno")
ax.add_collection(pc)
ax.set_title("SFCO2 Poly Collection")
ax.set_global()
ax.set_extent((-180, 180, -90, 90), crs=ccrs.PlateCarree())
plt.colorbar(pc)
```

<img width="1092" alt="image" src="https://github.com/UXARRAY/uxarray/assets/67855069/7d847155-81a1-4746-ab4a-4c0bc03ae932">

**Comment by philipc2** [comment]
Wondering if these `to_polycollection` and `to_linecollection` methods would be sufficient as an interface for Matplotlib. We could consider adding an "alternative" `.plot()` method that uses Matplotlib directly, but this would require some significant work on our end. Could look something like.

```Python
import uxarray as ux

uxds = ...

ux.set_plotting_backend("matplotlib")

# use MPL
uxds['t2m'].plot()

ux.set_plotting_backend("holoviews")

# use HoloViews 
uxds['t2m'].plot()

**Comment by whannah1** [comment]
> Another example using our `to_polycollection()` method.
> 
> ```python
> pc, _ = uxds['SFCO2'][0].to_polycollection()
> 
> pc.set_transform(ccrs.PlateCarree())
> plt.figure(figsize=(20, 10))
> ax = plt.axes(projection=ccrs.Robinson())
> pc.set_cmap("inferno")
> ax.add_collection(pc)
> ax.set_title("SFCO2 Poly Collection")
> ax.set_global()
> ax.set_extent((-180, 180, -90, 90), crs=ccrs.PlateCarree())
> plt.colorbar(pc)
> ```

I can't get this to work - I'm getting a blank plot or a single vertical line - I tried modifying a few things and got a plot a few times, but the projection seemed to be ignored in one case and in other cases the coordinates were flipped or shifted.

Why are two projections (Robinson and PlateCarree) being used in that example?

**Comment by philipc2** [comment]
> Why are two projections (Robinson and PlateCarree) being used in that example?

`pc.set_transform(ccrs.PlateCarree())` sets the original projection of the data we are working with, and `ax = plt.axes(projection=ccrs.Robinson())` sets our destination projection

> I can kind of get this to work - but when I change things slightly I'm getting a blank plot or a single vertical line or flipped coordinates.

There are indeed a few bugs with this; we haven't maintained it in over a year. Working on getting some fixes out right now. Wonder what changes you made?

**Comment by xylar** [comment]
@philipc2 and @whannah1, my understanding is that PolyCollection is still not really supported as a GeoAxis in Cartopy yet.  That's something that @andrewdnolan, a postbac with us at LANL, is working on.  @andrewdnolan, can you say more about that?

**Comment by whannah1** [comment]
> `pc.set_transform(ccrs.PlateCarree())` sets the original projection of the data we are working with

The cube sphere data doesn't have an inherent projection, right? So the idea of an "original projection" is confusing.

I tried changing the projection to Mollewiede (see example below) but I just get a blank rectangle. My first thought was that the extent needed to be adjusted to match the center longitude that I usually use, but using 0:360 in `set_extent` made no difference. 

```
map_proj = ccrs.Mollweide(central_longitude=180)
pc.set_transform(ccrs.PlateCarree())
pc.set_cmap("inferno")
plt.figure(figsize=(20, 10))
ax = plt.axes(projection=map_proj)
ax.add_collection(pc)
ax.set_global()
ax.set_extent((-180, 180, -90, 90), crs=map_proj)
plt.colorbar(pc)
plt.savefig(fig_file)
```

**Comment by philipc2** [comment]
> > `pc.set_transform(ccrs.PlateCarree())` sets the original projection of the data we are working with
> 
> The cube sphere data doesn't have an inherent projection, right? So the idea of an "original projection" is confusing.
> 
> On thing I tried was to change the projection to Mollewiede (see example below) but I just get a blank rectangle. My first thought was that the extent needed to be adjusted to match the center longitude that I usually use, but using 0:360 in `set_extent` made no difference.
> 
> ```
> map_proj = ccrs.Mollweide(central_longitude=180)
> pc.set_transform(ccrs.PlateCarree())
> pc.set_cmap("inferno")
> plt.figure(figsize=(20, 10))
> ax = plt.axes(projection=map_proj)
> ax.add_collection(pc)
> ax.set_global()
> ax.set_extent((-180, 180, -90, 90), crs=map_proj)
> plt.colorbar(pc)
> plt.savefig(fig_file)
> ```

```Python
pc = uxds['SFCO2'][0].to_polycollection(periodic_elements='exclude', override=True)
pc.set_transform(ccrs.PlateCarree())
plt.figure(figsize=(20, 10))
ax = plt.axes(projection=ccrs.Mollweide())
ax.coastlines()
pc.set_cmap("coolwarm")
ax.add_collection(pc)
ax.set_title("SFCO2 Poly Collection")
ax.set_global()
plt.colorbar(pc)
```

<img width="1154" alt="image" src="https://github.com/UXARRAY/uxarray/assets/67855069/4fa1c8c5-5901-4696-a220-f5a443c4ee5b">


This fixed it for me. The `set_global()` and `set_extent` were conflict with eachother. I removed the `set_extent` and it works as expected.

**Comment by philipc2** [comment]
#844 will update the `to_polycollection()` and `to_linecollection()`, fixing a few bugs and improving the parameters to be in line with our design.

Working on a user guide section as well (example from the PR)

https://uxarray--844.org.readthedocs.build/en/844/user-guide/mpl.html

**Comment by whannah1** [comment]
@philipc2 it appears that your plot is messed up somehow. I've been using the PRECC variable since I'm more familiar with how it should look, and there should be large values in the Tropics, but at one I got something like this where it was only showing data around the north pole associated with one of the cube faces.

**Comment by philipc2** [comment]
> @philipc2 it appears that your plot is messed up somehow with those sharp lines over north america and russia. I've been using the PRECC variable since I'm more familiar with how it should look, and there should be large values in the Tropics, but at one I got something like this where it was only showing data around the north pole associated with one of the cube faces.

Your right, didn't notice that at first. Looking into it.

**Comment by andrewdnolan** [comment]
Hi all. Was just about to chime in! 

As a first note, I was aware of the `to_polycollection()` method but have not been able to operationally use it since it's pretty slow. As a realistic example using the `mpaso.IcoswISC30E3r5.20231120` mesh for MPAS-Ocean the `.to_polycollection()` method takes ~4.5 minutes. From my understanding for scientific purposes that mesh is coarsest production mesh used by MPAS-O. 
```python
import uxarray as us  
primal_mesh = ux.open_grid("mpaso.IcoswISC30E3r5.20231120.nc", use_dual=False)

%time primal_polycollection = primal_mesh.to_polycollection()
```
```bash
CPU times: user 4min 23s, sys: 1.47 s, total: 4min 24s
Wall time: 4min 25s
``` 

For contrast, the [package](https://github.com/andrewdnolan/mosaic/tree/initial-release) I've been working on is able to great the patches for that mesh in < 1 second.

```python
import xarray as xr 
from mosaic.descriptor import Descriptor

ds = xr.open_dataset("mpaso.IcoswISC30E3r5.20231120.nc").isel(Time=-1, nVertLevels=0)

descriptor = Descriptor(ds)

# The patches (cell, edge, vertex) are attributes but lazily loaded, which is why the timing is here. 
%time cell_patches = descriptor.cell_patches
```
```bash
CPU times: user 47.9 ms, sys: 28.2 ms, total: 76.1 ms
Wall time: 75.3 ms
```
---

P.S. you can get that mesh [here](https://web.lcrc.anl.gov/public/e3sm/inputdata/ocn/mpas-o/IcoswISC30E3r5/). Or by running: 
```
$ curl https://web.lcrc.anl.gov/public/e3sm/inputdata/ocn/mpas-o/IcoswISC30E3r5/mpaso.IcoswISC30E3r5.20231120.nc -o mpaso.IcoswISC30E3r5.20231120.nc 
```

**Comment by andrewdnolan** [comment]
Onto @xylar's point about using `PolyCollection` objects with`GeoAxis`. From rooting around in `cartopy` a little bit, my understanding is the only `matplotlib.collection` type that `cartopy` supports is  [`QuadMesh`](https://github.com/SciTools/cartopy/blob/main/lib/cartopy/mpl/geocollection.py). 

But, I could be wrong. Given the performance bottleneck I've never actually tried plotting the `PolyCollection` generated. When I try I'm getting some errors, but I don't have the most up to date version of `uxarray`. Working on updating that now and will share a m.w.e. and errors (if they still happen) in a little bit.

**Comment by philipc2** [comment]
Hi @andrewdnolan 

Our primary bottleneck for visualization right now is how we handle elements along the antimeridian. We've been using the [`antimeridian`](https://github.com/gadomski/antimeridian) package, but have considered writing our own correction method, like what you have done. In practice, there's roughly a 20 times performance hit to correct the elements using this package.

The most recent iteration to `to_polycollection()` in #844 adds an optional parameter to determine how to handle these elements. 

![image](https://github.com/UXARRAY/uxarray/assets/67855069/30be3c24-7665-4366-8ba6-c07f9ef16c7d)

Using `periodic_elements='exclude'`, the timining is much closer to what is desired. This is using the grid file you provided on an M1 Macbook with 32GB of memory for reference. 

<img width="569" alt="image" src="https://github.com/UXARRAY/uxarray/assets/67855069/17d65a69-6a49-402f-aa69-4c98e1f6ca2e">


### Global (hard to see edges with this view)

<img width="1540" alt="image" src="https://github.com/UXARRAY/uxarray/assets/67855069/3f06732f-707c-48b8-a5ff-7813de41b3e3">



### Zoomed
<img width="1540" alt="image" src="https://github.com/UXARRAY/uxarray/assets/67855069/0199519f-9d2f-467b-becb-1c7ab5391537">

**Comment by philipc2** [comment]
@andrewdnolan 

Would love to connect sometime and chat about how you've handled the antimeridian elements, as that is really our main limitation as of now.

**Comment by philipc2** [comment]
@whannah1 

Not sure why the Mollweide projection is having issues, but I've had no issues with a few other projections

### Works as Expected

<img width="517" alt="image" src="https://github.com/UXARRAY/uxarray/assets/67855069/e4e41884-a8d7-4ae0-a8ff-a0f2169ea7da">

<img width="757" alt="image" src="https://github.com/UXARRAY/uxarray/assets/67855069/739ab002-ed7f-440b-b0fb-501a3820fb28">

<img width="550" alt="image" src="https://github.com/UXARRAY/uxarray/assets/67855069/3e1b8291-947a-47e0-9857-c4005c83685d">

<img width="522" alt="image" src="https://github.com/UXARRAY/uxarray/assets/67855069/d9c65b0c-a5c6-4d72-8839-dc340c86e8d1">


### Not as Expected

<img width="805" alt="image" src="https://github.com/UXARRAY/uxarray/assets/67855069/b3849959-758e-42f6-b95d-ee1e27edfe46">

<img width="805" alt="image" src="https://github.com/UXARRAY/uxarray/assets/67855069/fc39e9d1-ea02-436c-8dd5-22c4a91d7ac1">

**Comment by whannah1** [comment]
@philipc2 the last example there seems to have a problem of data being cutoff. You should really use a different variable and maybe a brighter colormap to help make these issues more noticeable.

**Comment by andrewdnolan** [comment]
@philipc2 Short answer is I don't fully resolve the antimeridian problem. I correct the vertex location of the elements that cross the antimeridian, but that leaves a zipper like pattern mirrored over the y-axis. But in reality, for any scientifically useful mesh resolution you can't see the missing cells when globally plotting. 

It would be great to sit down and chat about different approaches to the antimeridian problem, and how our work might be melded together! 

----

Took me a second to get it up and running, but I can confirm the branch you linked #844 dramatically speeds up the `PolyCollection` creation. 

Unfortunately I'm seeing some strange patterns in the rendered plots. I'm using: 
```python
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
import uxarray as ux
import xarray as xr

transform = ccrs.PlateCarree()
projection = ccrs.PlateCarree()

ds = xr.open_dataset("mpaso.IcoswISC30E3r5.20231120.nc").isel(Time=-1, nVertLevels=0)
primal_mesh = ux.open_grid("mpaso.IcoswISC30E3r5.20231120.nc", use_dual=False)

collection = primal_mesh.to_polycollection(periodic_elements='exclude')

collection.set_transform(transform)
collection.set_antialiased(False)
collection.set_array(ds["temperature"])
collection.set_cmap("viridis")

fig, ax = plt.subplots(1, 1, figsize=(15,7), facecolor="w",
                       constrained_layout=True,
                       subplot_kw=dict(projection=projection))


ax.coastlines()
ax.add_collection(collection)
ax.set_global()
fig.colorbar(collection, label="Temperature")
```
which results in: 
![PlateCarrreeProjection_mpaso IcoswISC30E3r5 20231120](https://github.com/UXARRAY/uxarray/assets/32367657/d85cf9ef-8f62-4236-b3ee-03a8c962e68d)


Does the `to_polycollection` method do some kind of permuting on the cell ordering? Because if I don't set the collection's array then I'm able to reproduce what you shared above:
![NoDATA_PlateCarrreeProjection_mpaso IcoswISC30E3r5 20231120](https://github.com/UXARRAY/uxarray/assets/32367657/da322c03-d17f-4128-83a3-37b68a4298b2)

**Comment by philipc2** [comment]
@andrewdnolan 

Yes, when `periodic_elements='exclude'`, the elements that would cause artifacts are simply dropped from the resulting plot. 

Here's an update example using our `open_dataset` method to create a `UxDataset`, which should be familar to any Xarray interface.

```Python
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
import uxarray as ux

transform = ccrs.PlateCarree()
projection = ccrs.PlateCarree()

# open a UxDataset
uxds = ux.open_dataset("/Users/philipc/Downloads/mpaso.IcoswISC30E3r5.20231120.nc",
                       "/Users/philipc/Downloads/mpaso.IcoswISC30E3r5.20231120.nc")


# create a Poly Array from a 1D slice of a face-centered data variable
collection = uxds['temperature'].isel(Time=0, nVertLevels=0).to_polycollection(periodic_elements="exclude")

collection.set_transform(transform)
collection.set_antialiased(False)
collection.set_cmap("viridis")

fig, ax = plt.subplots(1, 1, figsize=(15,7), facecolor="w",
                       constrained_layout=True,
                       subplot_kw=dict(projection=projection))


ax.coastlines()
ax.add_collection(collection)
ax.set_global()
fig.colorbar(collection, label="Temperature")
```

<img width="1510" alt="image" src="https://github.com/UXARRAY/uxarray/assets/67855069/cb81e364-7646-41cc-8d46-038bcc146e57">

Heres the source code with the indices being used.

https://github.com/UXARRAY/uxarray/blob/17b950ec5701724c5d7e934675fddbb203afd04e/uxarray/core/dataarray.py#L183-L220

**Comment by andrewdnolan** [comment]
@philipc2 Awesome! Thanks for catching my mixup there. 

So, the next question / problem I have might be realted to the projection problem that you and @whannah1 have brought up. 

Using the `mpaso.IcoswISC30E3r5.20231120` mesh, @philipc2 how long does it take you to plot wtih projection other than `ccrs.PlateCarree`? For me it takes a really long time, using ` ccrs.RotatedPole ` it takes >11 minutes!

I think this is because `PolyCollections` aren't really supported by `cartopy`. When you set the transform for the collection (e.g.  `collection.set_transform(transform)`) it's using the `matplotlib` transform method, not `caropty`'s methods for transforming coordinates. 

For those troublesom projections, I wonder if the problems would persist if you created `QuadMesh` collections, which are supported by `cartopy`, instead of `PolyCollections`.  What mesh are you using for those plots? It'd be great to play around with those and see if I can better demonstrate what I mean.

**Comment by philipc2** [comment]
> @philipc2 Awesome! Thanks for catching my mixup there.
> 
> So, the next question / problem I have might be related to the projection problem that you and @whannah1 have brought up.
> 
> Using the `mpaso.IcoswISC30E3r5.20231120` mesh, @philipc2 how long does it take you to plot wtih projection other than `ccrs.PlateCarree`? For me it takes a really long time, using `ccrs.RotatedPole` it takes >11 minutes!
> 
> I think this is because `PolyCollections` aren't really supported by `cartopy`. When you set the transform for the collection (e.g. `collection.set_transform(transform)`) it's using the `matplotlib` transform method, not `caropty`'s methods for transforming coordinates.
> 
> For those troublesome projections, I wonder if the problems would persist if you created `QuadMesh` collections, which are supported by `cartopy`, instead of `PolyCollections`. What mesh are you using for those plots? It'd be great to play around with those and see if I can better demonstrate what I mean.

Let it run in the background and this is what I got. Usually it takes a bit more time to actually show up in the notebook though. 


<img width="1523" alt="image" src="https://github.com/UXARRAY/uxarray/assets/67855069/3aa312f2-26b5-4bda-acb0-ccb1bb8e8f23">

**Comment by philipc2** [comment]
I haven't use Matplotlib much for plotting unstructured grids. Wonder if there is a way to rasterize the `PolyCollection`, something similar to what Datashader does, since there is no point in plotting every polygon for such a high resolution grid.

**Comment by rajeeja** [comment]
> I haven't use Matplotlib much for plotting unstructured grids. Wonder if there is a way to rasterize the `PolyCollection`, something similar to what Datashader does, since there is no point in plotting every polygon for such a high resolution grid.

`from matplotlib.collections import PolyCollection` PolyCollection has a `.set_rasterized(True)` will this do it?

**Comment by andrewdnolan** [comment]
Hi @rajeeja! 

I think that only take effect when the figure is saved to a vector graphic format, see the the "Note" from `matplotlib` docs here: https://matplotlib.org/stable/gallery/misc/rasterization_demo.html

But, I don't think the significant overhead when using a projection has to do with the rendering of each individual polygon. If that were the case, then there would be a similar overhead when using no projection (or `projection` == `transform`), which isn't the case (at least for me). When plotting the MPAS data with a `PlateCarree` projection it takes seconds, but using any other kind of projections it takes on the order of 5 minutes. 

I think this has to do with the way the geographic transform is used by `PolyCollection`, which isn't explicitly supported by `cartopy` (I think). I'm working on a demo with some cubed sphere data in order to demonstrate some timing differences when using `PolyCollection` versus `QuadMesh`, which is supported by `cartopy`. I'll be back in touch soon once that's worked out.

**Comment by rajeeja** [comment]
> Hi @rajeeja!
> 
> I think that only take effect when the figure is saved to a vector graphic format, see the the "Note" from `matplotlib` docs here: https://matplotlib.org/stable/gallery/misc/rasterization_demo.html
> 
> But, I don't think the significant overhead when using a projection has to do with the rendering of each individual polygon. If that were the case, then there would be a similar overhead when using no projection (or `projection` == `transform`), which isn't the case (at least for me). When plotting the MPAS data with a `PlateCarree` projection it takes seconds, but using any other kind of projections it takes on the order of 5 minutes.
> 
> I think this has to do with the way the geographic transform is used by `PolyCollection`, which isn't explicitly supported by `cartopy` (I think). I'm working on a demo with some cubed sphere data in order to demonstrate some timing differences when using `PolyCollection` versus `QuadMesh`, which is supported by `cartopy`. I'll be back in touch soon once that's worked out.

Thanks for link, it might be that matplotlib optimizes some projections and not all or the support for other libraries in not optimized as you state.

**Comment by philipc2** [comment]
I've also had similar performance issues with projecting polygons when using GeoViews, so it might be the case that applying projections to Polygons is simply more expensive than applying to to a QuadMesh or similar type of grid.

I believe that projecting the data **_prior_** to creating a PolyCollection might be a better approach.

**Comment by philipc2** [comment]
If we project before visualization, even if there is a moderate overhead, it would only be a one-time computation. Something like the following would be good to have for UXarray.

```Python
uxgrid = ux.open_grid(...)

# in-place projection
uxgrid.set_projection("Robinson")

# fluent projection (return a new Grid)
uxgrid_rob = uxgrid.project("Robinson")

# should now be able to plot without needing to apply any other projections
uxgrid_rob.to_polycollection()
```

**Comment by andrewdnolan** [comment]
That's exactly what I'm doing in [`mosiac`](https://github.com/andrewdnolan/mosaic/blob/initial-release/mosaic/descriptor.py)! Yeah I definitely think that's the best approach. Plus if you have multiple subplots you don't (with the same projection), you don't have to do the same projection operation multiple time. 

Another benefit is if your doing it to the coordinate arrays, those are usually much smaller than the polygon arrays. Using `MPAS` variable names and just considering cell centered values as an example you'll have two coordinate arrays which are `nCells` long (i.e. `lonCell` and `latCell`), i.e `2*nCells` values to transform. Whereas, for the polygon patches those will have dimensions `nCells` x `maxEdges` x `2`, where `maxEdges` could be somewhere 6 and 8 in practice. So by transforming the patches you'd be doing 6--8 times the work necessary to transform coordinates.

**Comment by philipc2** [comment]
> That's exactly what I'm doing in [`mosiac`](https://github.com/andrewdnolan/mosaic/blob/initial-release/mosaic/descriptor.py)! Yeah I definitely think that's the best approach. Plus if you have multiple subplots (with the same projection), you don't have to do the same projection operation multiple time.
> 
> Another benefit is if your doing it to the coordinate arrays, those are usually much smaller than the polygon arrays. Using `MPAS` variable names and just considering cell centered values as an example you'll have two coordinate arrays which are `nCells` long (i.e. `lonCell` and `latCell`), i.e `2*nCells` values to transform. Whereas, for the polygon patches those will have dimensions `nCells` x `maxEdges` x `2`, where `maxEdges` could be somewhere between 6 and 8 in practice. So by transforming the patches you'd be doing 6--8 times the work necessary to transform coordinates, c.f. transforming the coordinates array directly once.

One of the reasons we didn't move forward with supporting these types of projections early was our method of handling faces around the antimeridian. We use the `[antimeridian](https://github.com/gadomski/antimeridian)` package, which limited us to defining the antimeridian as +- 180 degrees with the standard PlatteCaree projection.

**Comment by andrewdnolan** [comment]
So took me a little while to come up with a working example, but [ here's a notebook](https://gist.github.com/andrewdnolan/44b82763f854cd65cfb955dbcd44f25b) with some timing info for `PloyCollection` versus `QuadMesh`.   The big take away is: 
![timing](https://github.com/UXARRAY/uxarray/assets/32367657/63f89c17-7265-4143-9995-2b2daca1d98b)

The timing if for the same quadrilateral mesh (w/ ~40,000 cells), but plotted with the `PloyCollection` and `QuadMesh` methods respectively. *But*, directly comparing those isn't really fair since `QuadMesh` is super optimized. So, I first get the inherent time difference between `PloyCollection` and `QuadMesh`, when not using map projected data (i.e. no `GeoAxis`). I then normalize the `QuadMesh` time by this inherent overhead, so the columns to really compare are the orange and green. 

For the projections tested `PloyCollection` is 150 time slower, when using a `GeoAxis` than `QuadMesh` (normalized). I believe this has to do with [`QuadMesh` being explicitly supported](https://github.com/SciTools/cartopy/blob/main/lib/cartopy/mpl/geocollection.py) by `cartopy`, where `PloyCollection` isn't. 

Pre-transforming the coordinates to the project used before `PolyCollection` creation is definitely one way circumvent this problem, it's what I'm doing to address this aswell in [`mosaic`](https://github.com/andrewdnolan/mosaic/blob/initial-release/mosaic/descriptor.py). But I wonder if at some point we'll need to open a PR in `caropty` directly to add support for `PolyCollection`'s inorder to make this a bit more robust.

**Comment by philipc2** [comment]
Thanks for the great timing chart! By projecting the coordinates before creating a `PolyCollection`, the execution time went down to under 4 seconds for me. Going to push these changes soon to the branch in #844

```Python
%%time

projection = ccrs.Orthographic()

# create a Poly Array from a 1D slice of a face-centered data variable
collection = uxds['temperature'].isel(Time=0, nVertLevels=0).to_polycollection(override=True, periodic_elements="exclude", projection=projection)

pc = copy.deepcopy(collection)

pc.set_antialiased(False)
pc.set_cmap("viridis")

fig, ax = plt.subplots(1, 1, figsize=(15,7), facecolor="w",
                       constrained_layout=True,
                       subplot_kw=dict(projection=projection))


ax.coastlines()
ax.add_collection(pc)
ax.set_global()
fig.colorbar(pc, label="Temperature")
```

<img width="871" alt="image" src="https://github.com/user-attachments/assets/f4c0ec5f-676d-4b17-81f4-9425b9006b39">
