### ISSUE TITLE
Missing version info

### ISSUE THREAD

**Issue by kafitzgerald** [UXARRAY/uxarray#919]
### Version

latest version from conda-forge

### How did you install UXarray?

Conda

### What happened?

I was expecting `ux.__version__` to return the current version info for the package.  Instead, I get `'0.0.0'`.

It looks like only the Conda version is impacted (works fine when installing via pip).

### What did you expect to happen?

See above.  

### Can you provide a MCVE to repoduce the bug?

```python
import uxarray as ux
ux.__version__
```

**Comment by philipc2** [comment]
Hi @kafitzgerald 

Thanks for catching this! Since it only appears to be an issue with `conda` installs, I wonder if something might be configured incorrectly in our [feedstock repo](https://github.com/conda-forge/uxarray-feedstock).

Comparing to Xarray's feedstock, this immediately jumped out as a difference:

https://github.com/conda-forge/xarray-feedstock/blob/25fb1d1c91dc951102425b2293d1120192ba9677/recipe/meta.yaml#L1-L2

Maybe the lack of `{% set name = "uxarray" %}` leads to `importlib.metadata` producing an incorrect `0.0.0` version is some form of fallback version?

**Comment by kafitzgerald** [comment]
I suspect it might be that you're missing setuptools_scm from your host requirements in the meta.yml.

**Comment by philipc2** [comment]
After those changes, we're now getting `999` as our version number. Any thoughts @kafitzgerald ?

**Comment by philipc2** [comment]
#921 has fixed the issue!

![image](https://github.com/user-attachments/assets/043eaadc-bfe8-427b-8702-7ecb2d15d4ef)
