### ISSUE TITLE
standardize njit and jit-cache usage across the project, cleanup and use JIT related constants in constants.py

### ISSUE THREAD

**Issue by rajeeja** [UXARRAY/uxarray#969]
### Proposed new feature or change:

codecov doesn't work correctly and track @njit decorated functions, a way to enable disable numba across the project would be useful.

**Comment by rajeeja** [comment]
custom decorator
```

# Custom decorator to enable/disable numba
def optional_numba_jit(nopython=True, parallel=False, cache=False, fastmath=False):
    def decorator(func):
        if USE_NUMBA:
            return numba.jit(nopython=nopython, parallel=parallel, cache=cache, fastmath=fastmath)(func)
        else:
            return func
    return decorator
```

**Comment by rajeeja** [comment]
Hey @aaronzedwick can you put the final observations from the Friday meeting here:?
Thanks!

**Comment by aaronzedwick** [comment]
Sure @rajeeja. When the package is imported, it seems that all the functions are pre-loaded. Or, it could be just when a function is called for the first time. Either way though, when we change our enable_jit variable and use our wrapper to use just the normal version of the function, it doesn't do anything because that function already has the wrapper applied. And it is just going to use that version of the function. We would have to find a way to reload the functions that are loaded with the wrapper, and rewrap them. So we decided it was best to just put this on pause, as the code coverage is just a number, and as long as we are using it properly to identify where we have holes in our testing, it doesn't really matter what that number is too much.
